import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs"
import { ThemeProvider } from "@/components/theme";
import ReactQueryProvider from "@/react-query";
import { Manrope, DM_Sans } from 'next/font/google'

import { Toaster } from "sonner";
import { ReduxProvider } from "@/redux/provider";
const manrope = DM_Sans({ subsets: ['latin'] })


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

   
    
    <html lang="en">
      <body
         className={`${manrope.className} bg-[#171717]`}>

      
       
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <ReduxProvider>

         
        <ReactQueryProvider>
        {children}
        <Toaster/>
        </ReactQueryProvider>
        </ReduxProvider>
        </ThemeProvider>
       
       
      </body>
    </html>
    </ClerkProvider>
  );
}
